#!/bin/sh
#Barry Kauler, for Puppy Linux v2.17. LGPL.
#BK updated for 3.01
#v3.94 14 dec 2007 BK updated.
#v3.98 bugfix. w462 small mods.
#w471 add 'cupsview'.
#w480 bugfix if still using old cups.
#w482 general update, now using html help viewer.
#091126 bugfix if using seamonkey/firefox ui for cups.
#100809 bugfix if chrome is defaultbrowser in lupu, use gtkmoz #01micko

USEBROWSER="defaultbrowser"
[ -f /usr/bin/netsurf-barewindow ] && USEBROWSER="netsurf-barewindow"
[ -f /usr/local/bin/bareview ] && USEBROWSER="bareview" #from gtkmoz pkg.
[ -f /usr/local/bin/cupsview ] && USEBROWSER="cupsview" #w471 from gtkmoz pkg.

if [ "`grep "chrome" /usr/local/bin/defaultbrowser`" != "" ];then USEBROWSER="gtkmoz" #chrome won't run cups, a bug in chrome
fi

#v3.98 'lpr' is a script in cups package, comment this out...
##v2.17.1 PDQ print system has lpr symlink to /usr/bin/pdq, set in /usr/sbin/printerwizard.sh,
##so may have to change it back...
#rm -f /usr/bin/lpr
#ln -s lpr-cups /usr/bin/lpr

#v2.20 warning the defaultbarehtmlviewer must support css.

#Xdialog --yesno "Do you want to add a new printer?" 0 0
#if [ $? -ne 0 ];then
 #is cupsd running?...
 if [ "`pidof cupsd`" = "" ];then
  #[ -f /etc/rc.d/rc.cups ] && /etc/rc.d/rc.cups start
  #[ -f /etc/init.d/cups ] && /etc/init.d/cups start
  /etc/init.d/cups start
 fi
 #exec defaultbarehtmlviewer http://localhost:631/
 exec $USEBROWSER http://localhost:631/
#fi

#xmessage -bg "medium purple" -title "CUPS Web Interface Help" -center "
#Your default browser should have opened (or will open after 3-30 seconds) with the CUPS
#web interface. Here you can add and configure your printer.
#
#IMPORTANT: If asked for a username and password, enter 'root' and 'woofwoof'.
#
#Click on 'Manage Printers', then 'Add Printer'. Enter a name for your printer, e.g. 
#HL1030. The 'Location' and 'Description' fields can be left blank. Click 'Continue'.
#
#The steps after that should be straightforward, and hopefully you will find a printer
#driver that works for you. Finally you should see the message:
# 'Printer HL1030 has been added successfully.'
#
#- If no suitable printer is found, check www.linuxprinting.org for a .ppd file for your
#printer. When you have downloaded it, just copy it to the /usr/share/ppd directory
#and run this program again (from the System menu). Note, there is also a PET package,
#'hpijs-1.7' with more Hewlett Packard printer drivers.
#
#Click on 'Printers', 'Configure Printer' to change 'Page Size' (if needed) and 'Resolution'
#(600 DPI is good). Click 'Continue', then 'Printers' again. The 'Printer State' should be
#'idle, accepting jobs.'
#
#Finally, click 'Print Test Page' to see if your printer works." &

basichtmlview file:///usr/share/doc/cups_shell.htm & #w482

#killall cupsd
/etc/init.d/cups stop

#note, /us/share/ppd may not be needed anymore...
mkdir -p /usr/share/cups/model/gutenprint/5.0 #old gutenprint pkg.
mkdir -p /usr/share/ppd/gutenprint/5.0 #old gutenprint pkg.
mkdir -p /usr/share/cups/model/gutenprint/5.2
mkdir -p /usr/share/ppd/gutenprint/5.2

#w480, need to run cups-genppd if old cups...
CUPSVERSION=""
[ "`which cups-config`" != "" ] && CUPSVERSION="`cups-config --version`"
if [ "$CUPSVERSION" = "1.1.23" ];then
 yaf-splash -font "8x16" -outline 0 -margin 4 -bg orange -placement top -text "Please wait, composing Gutenprint '.ppd' driver files..." &
 X1PID=$!
 [ "`which cups-genppd.5.0`" != "" ] && cups-genppd.5.0
 [ "`which cups-genppd.5.2`" != "" ] && cups-genppd.5.2
 kill $X1PID
fi

sync

#/usr/sbin/cupsd
/etc/init.d/cups start
sleep 4 #091126 increase.

#mv /usr/share/cups/model/gutenprint/5.0/*.gz /usr/share/cups/model/gutenprint/5.0/C/

#defaultbarehtmlviewer http://localhost:631/
$USEBROWSER http://localhost:631/ 2>/tmp/cups-shell-ui-fail
#091126 seamonkey/ff already started above, for help page, but slow to startup...
CNT=0
while [ "`grep "Failed to send command" /tmp/cups-shell-ui-fail`" ];do
 sleep 4
 $USEBROWSER http://localhost:631/ 2>/tmp/cups-shell-ui-fail
 CNT=`expr $CNT + 1`
 [ $CNT -gt 7 ] && break
done

#rm -rf /usr/share/cups/model/gutenprint/5.0/C
if [ "$CUPSVERSION" = "1.1.23" ];then #w480
 rm -rf /usr/share/cups/model/gutenprint/5.0/* 2>/dev/null #old gutenprint pkg.
 rm -rf /usr/share/ppd/gutenprint/5.0/* 2>/dev/null #old gutenprint pkg.
 rm -rf /usr/share/cups/model/gutenprint/5.2/* 2>/dev/null
 rm -rf /usr/share/ppd/gutenprint/5.2/* 2>/dev/null
fi

###END###
