#!/bin/sh
#Barry Kauler GPL 2007.
#called from pupdial.
#v405 july 2008: total overhaul.
#v465 rerwin: v413 added module names for wireless modems
#v477 rerwin: v413 handle both lspci formats (replacing v003).
#v477 rerwin: v413 added more module names for wireless modems

if [ -h /dev/modem ];then
 MODEMDEV="`readlink /dev/modem`"
 MSGMDM3="
PORT: /dev/modem is currently linked to port ${MODEMDEV}."
#v433 check for bluetooth modem and set as /dev/modem...
else
 MSGMDM3=""
 if which rfcomm >/dev/null && which sdptool >/dev/null;then  
  DUNPATTERN="`sdptool search DUN | sed -n -e '/^Searching/h' -e '/^    Channel:/{H;x}' -e 's/Searching for DUN on //' -e 's/ ...\n    Channel://p'`"
  if [ "$DUNPATTERN" != "" ];then
   DUNRFCLIST="`rfcomm -a | grep ' connected' | sed -e 's/ channel//' | grep -F "$DUNPATTERN" | cut -f 1 -d :`"
   if [ "$DUNRFCLIST" != "" ];then
    DUNRFCOMM="`echo "$DUNRFCLIST" | head -n 1`"
    ln -snf $DUNRFCOMM /dev/modem
   fi
  fi
#  echo "Modemprobe: DUNPATTERN: $DUNPATTERN  DUNRFCLIST: $DUNRFCLIST  DUNRFCOMM: $DUNRFCOMM" >> /tmp/udevtrace-modem.log #debug
 fi #v433 end
fi

#find all loaded modem modules...
KERNVER=`uname -r` #v433
ALSAMODEMINFO="`cat /proc/asound/pcm 2>/dev/null | grep ' Modem :'`"
USBSERIALMODS="" #v433
lsmod | grep -q '^usbserial ' \
 && USBSERIALMODS=" `grep -w 'usbserial.ko' /lib/modules/$KERNVER/modules.dep | grep -o '^[^:]*' | rev | cut -f 1 -d / | rev | sed -e 's/\.ko$//' -e 's/^/\|\^/' | tr '\n' ' '`" #v433
MODEMMODS="`lsmod | grep -E "^agrserial |^cdc_acm |^esscom |^Intel536 |^[iI]ntel537 |^intel537[ES][AP] |^ltserial |^martian_dev |^mwave |^pctel |^slamr |^slusb |^snd_via82xx_modem |^snd_atiixp_modem |^snd_intel8x0m |^snd_hda_intel |^dgcusbdcp |^hso |^ipwireless |^nozomi |^hcfpcihw |^hsfcadmus2 |^hsfcadmus2smart |^hsfmc97ali |^hsfmc97ati |^hsfmc97ich |^hsfmc97sis |^hsfmc97via |^hsfpcibasic2 |^hsfpcibasic2bry |^hsfpcibasic2hsfi |^hsfpcibasic2smart |^hsfpcibasic3 |^hsfusbcd2 |^rfcomm$USBSERIALMODS" | cut -f 1 -d ' '`" #v413 v416 v432 v433
[ "$ALSAMODEMINFO" = "" ] && MODEMMODS="`echo "$MODEMMODS" | grep -v '^snd_'`"
SNDMOD="`echo "$MODEMMODS" | grep '^snd_' | head -n 1`"
#v413 For usbserial, reject it unless force-loaded with vendor ID (for usb modems).
[ "`grep '^ADDLIST=' /etc/rc.d/MODULESCONFIG | grep ' usbserial:vendor='`" = "" ] && MODEMMODS="`echo "$MODEMMODS" | grep -v '^usbserial$'`" #v413
MODEMMODS="`echo "$MODEMMODS" | sort | tr '\n' ' '`"
MMCNT=`echo "$MODEMMODS" | wc -w`

MSGMDM2=""
#if [ "$SNDMOD" != "" ];then
# MSGMDM2="
#Note that ${SNDMOD} is an ALSA sound driver but it also supports an on-board modem (port ttySL0)."
#fi

case $MMCNT in
 0)
#v412 Check for any driver of a modem that is not detected automatically.
#v433 This check is no longer valid, since any such modem is now supported through the udev rules file /etc/udev/rules.d/60-dialup-modem.rules and, thus, will have its driver loaded. Logic removed.
 MSGMDM1="Well, Puppy did not detect anything at bootup, so if the modem was turned-on then it probably is not supported by any of the drivers in Puppy. Tough, you need to get another modem -- an old serial modem is best. There are some USB modems that work well."
 ;;
 1)
  MSGMDM1="Puppy did detect a modem at bootup, and loaded this driver:
${MODEMMODS}${MSGMDM2}${MSGMDM3}"
 ;;
 *)
  MSGMDM1="Puppy detected more than one modem at bootup and and loaded these drivers:
${MODEMMODS}${MSGMDM2}${MSGMDM3}"
 ;;
esac



export MAINDIALOG="
<window title=\"PupDial modem selection\" icon-name=\"gtk-connect\">
 <vbox>

  <hbox>
   <text  use-markup=\"true\"><label>\"<b>Click this button to use the 'wvdialconf' program to automatically probe and setup a modem for use by PupDial. If successful will create or update /etc/wvdial.conf and will set /dev/modem as a link to the correct modem port:</b>\"</label></text>
   <button>
    <label>PROBE</label>
    <action type=\"exit\">SETUP</action>
   </button>
  </hbox>
 
 <frame Manual probing>
 
  <text><label>The above does a fully automatic probe, however if it is unsatisfactory you can consider some manual probing and setup...</label></text>
 
  <frame Serial hardware modem>
  <hbox>
   <text><label>If you have a true-hardware external serial or internal ISA card (or in some rare cases an internal PCI card), or think you might, click a button to probe. Note that 'ttyS0' is the same as 'com1' in DOS/Windows. Note also, 'ttyS0' is the most likely port, unless you have some other serial device such as a mouse. If the test is succesful then you will be offered to set /dev/modem and basic setup of /etc/wvdial.conf. (Note that these modems are not autodetected at bootup by Puppy, but are probed by the automatic PROBE button above)</label></text>
   <vbox>
    <button>
     <label>ttyS0</label>
     <action>/usr/sbin/modemtest ttyS0 &</action>
     <action type=\"exit\">TTYSN</action>
    </button>
    <button>
     <label>ttyS1</label>
     <action>/usr/sbin/modemtest ttyS1 &</action>
     <action type=\"exit\">TTYSN</action>
    </button>
    <button>
     <label>ttyS2</label>
     <action>/usr/sbin/modemtest ttyS2 &</action>
     <action type=\"exit\">TTYSN</action>
    </button>
    <button>
     <label>ttyS3</label>
     <action>/usr/sbin/modemtest ttyS3 &</action>
     <action type=\"exit\">TTYSN</action>
    </button>
    <button>
     <label>ttyS4</label>
     <action>/usr/sbin/modemtest ttyS4 &</action>
     <action type=\"exit\">TTYSN</action>
    </button>
   </vbox>
  </hbox>
  </frame>
  
  <frame Autodetected modems>
   <hbox>
    <text><label>\"Most modems are autodetected by Puppy at bootup, but it has to be turned on! (or plugged in). ${MSGMDM1}\"</label></text>
    
   <vbox>
   <button>
    <label>HELP</label>
    <action>/usr/sbin/modemprobe_help &</action>
   </button>
   </vbox>
   </hbox>
  </frame>
  
  <hbox>
   <text><label>Click this button to blacklist a modem module. Note that you will then have to click the ERASE button, then reboot Puppy so that autodetection can re-occur.</label></text>
   <vbox>
   <button>
    <label>BLACKLIST</label>
    <action>/usr/sbin/bootmanager blacklist &</action>
   </button>
   </vbox>
  </hbox>
  <hbox>
   <text><label>Click this button to erase current modem settings. This will delete /dev/modem thus allowing a fresh auto-probe at bootup and will cancel the 'Modem' entry in /etc/wvdial.conf:</label></text>
   <vbox>
   <button>
    <label>ERASE</label>
    <action>/usr/sbin/modemprobe_erase</action>
   </button>
   </vbox>
  </hbox>
 
 </frame>
  
 </vbox>
</window>
"

#echo "$MAINDIALOG" >/tmp/MAINDIALOG
RETSTRING="`gtkdialog3 --program=MAINDIALOG`"
#echo "RETSTRING=$RETSTRING"

#v405 getting some weird stuff on stdout from gtkdialog3, fix...
#all lines must have format: variable="value" ...
xRETSTRING="`echo "$RETSTRING" | grep -E '^[a-zA-Z0-9]+=\".*\"$'`"

eval "$xRETSTRING"

[ "$EXIT" != "SETUP" ] && exit

yaf-splash -font "8x16" -outline 0 -margin 4 -bg orange -text "Please wait, probing for modems..." &
X1PID=$!

rm -f /tmp/wvdial.conf 2>/dev/null
##[ "$MODEMDEV" != "" ] && [ "`grep 'SYMLINK="modem"' /etc/udev/rules.d/00-*`" = "" ] && echo 'KERNEL=="$MODEMDEV", SYMLINK="modem"' > /etc/udev/rules.d/00-modem_symlink.rules #v416

#v4.06 begin
DEVM=""
[ -f /etc/wvdial.conf ] && CONFDIR="etc" || CONFDIR="tmp"
wvdialconf /$CONFDIR/wvdial.conf >/tmp/logwvdialprobe 2>&1
RETVAL=$?
if [ $RETVAL -eq 0 ];then #found a modem and set it in wvdial.conf
 if [ "`grep '/dev/modem' /$CONFDIR/wvdial.conf`" != "" ];then #modem = /dev/modem - substitute /dev/modem target
  SEDSCRIPT="s%/dev/modem%/dev/`readlink /dev/modem`%" #v416
  sed -i -e "$SEDSCRIPT" /$CONFDIR/wvdial.conf #v416
 elif [ "`grep '/dev/ttyS_' /$CONFDIR/wvdial.conf`" != "" ];then
  #Convert ttyS_ link name to actual node name (e.g., ttyS_536ep -> 536ep)
  TMPDEVM="`cat /$CONFDIR/wvdial.conf | tr -s ' ' | grep '^Modem = ' | head -n 1 | cut -f 3 -d ' ' | cut -f 3 -d '/'`" #file name
  if [ -h /dev/$TMPDEVM ];then #it's a link to the correct device node name
   SEDSCRIPT="s%/dev/$TMPDEVM%/dev/`readlink /dev/$TMPDEVM`%" #v416
   sed -i -e "$SEDSCRIPT" /$CONFDIR/wvdial.conf #v416
  fi
 fi
 DEVM="`cat /$CONFDIR/wvdial.conf | tr -s ' ' | grep '^Modem = ' | head -n 1 | cut -f 3 -d ' '`"
#v432 Add possible alternate modem device
 sed -i -e '/#Modem =/d' /$CONFDIR/wvdial.conf
 DEVMALT="`get_modem_alternate_device $DEVM`"
 [ "$DEVMALT" != "" ] \
  && aPATTERN="s%^Modem = .*%&\n#Modem = /dev/${DEVMALT}%" \
  && sed -i -e "$aPATTERN" /$CONFDIR/wvdial.conf #v432 end
else #v433
 [ "$MODEMDEV" = "" ] && rm -f /dev/modem #v433
fi
#v4.06 end

kill $X1PID

if [ "$DEVM" != "" ];then #4.06 probe found a modem (and not /dev/modem)
 xDEVM="`echo -n "$DEVM" | cut -f 3,4 -d '/'`"
 ln -snf $xDEVM /dev/modem #v4.06
 touch /tmp/.pupdial-modem_detected #v433
 
 if [ -f /tmp/wvdial.conf ];then
  grep -v '^;' /tmp/wvdial.conf > /etc/wvdial.conf
  rm -f /tmp/wvdial.conf
  echo 'Carrier Check = no
Dial Command = ATDT

[Dialer isp1]
Phone = MYISPPHONENUM
Username = MYUSERNAME
Password = MYPASSWORD

[Dialer isp1apn]
Init5 = AT+CGDCONT=1,\"IP\",\"\"

[Dialer isp2]
Phone = MY2ISPPHONENUM
Username = MY2USERNAME
Password = MY2PASSWORD

[Dialer isp2apn]
Init5 = AT+CGDCONT=1,\"IP\",\"\"

[Dialer pin]
Init1 = AT+CPIN=

[Dialer wireless]
#Init4 = AT+COPS=0,0,\"MYOPS\",
#Init6 = AT+CGEQMIN=1,4,64,384,64,384
#Init7 = AT+CGEQREQ=1,4,64,384,64,384
#Init8 = AT+CGDCONT?
#Init9 = AT+COPS?' >> /etc/wvdial.conf
 fi
else #v433
 rm -f /tmp/.pupdial-modem_detected #v433
fi

sync
#leafpad /tmp/logwvdialprobe
exit $RETVAL #v4.06 Notify caller whether wvdialconf found a modem
