#!/bin/sh
#BK dummy for now
#v407 install firmware tarball if not installed.
#100228 BK

[ "`which pgprs-setup`" != "" ] && exec pgprs-setup

#xmessage "Currently only works with the Multitech GPRS modem.
#If the MT GPRS modem is plugged in, Puppy should have loaded
#the 'firmware tarball' which includes the /usr/bin/mt-gprs-setup
#script. If it isn't there, you get this message."

#install firmware tarball...
cp -f /lib/modules/all-firmware/pgprs.tar.gz /tmp/
cd /tmp
tar -zxf pgprs.tar.gz
cp -a --remove-destination /tmp/pgprs/* /
sync
cd /

#/pinstall.pgprs.sh >/dev/null 2>&1 #execute script.
#rm -f /pinstall.pgprs.sh >/dev/null 2>&1

#note, pgprs-setup and pgprs-connect are in the firmware tarball.
exec pgprs-setup
