#!/bin/sh
#Barry Kauler www.puppylinux.com
#2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
#v411 modified network-connect button.
#100215 fix exit button.

#    <action>/usr/sbin/printerwizard.sh &</action>
#    <action>/usr/sbin/modem-wizard &</action>

#  <hbox>
#   <text>
#    <label>This Wizard Wizard is a guide to using the Wizards in Puppy</label>
#   </text>
#  </hbox>

#    <action>exit</action>

export WizardWizard="
<window title=\"Puppy Setup\" icon-name=\"gtk-preferences\">
 <vbox>

  <hbox>
   <text>
    <label>Configure Puppy for your country...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-font.xpm</input>
    <action>/usr/sbin/countrywizard &</action>
   </button>
  </hbox>

  <hbox>
   <text>
    <label>Configure startup of Puppy...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/module16.xpm</input>
    <action>/usr/sbin/bootmanager &</action>
   </button>
  </hbox>

  <hbox>
   <text>
    <label>Change the mouse and keyboard...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/Mouse.xpm</input>
    <action>/usr/sbin/input-wizard &</action>
   </button>
  </hbox>
  <hbox>
   <text>
    <label>Setup ALSA sound...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-speaker.xpm</input>
    <action>/usr/sbin/alsawizard &</action>
   </button>
  </hbox>
  <hbox>
   <text>
    <label>Setup the X video...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-x.xpm</input>
    <action>/usr/sbin/xserverwizard &</action>
   </button>
  </hbox>
  <hbox>
   <text>
    <label>Connect to Internet or Intranet...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/pc2www.xpm</input>
    <action>/usr/sbin/connectwizard yes &</action>
   </button>
  </hbox>
  <hbox>
   <text>
    <label>Setup CUPS printing...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/tb_print.xpm</input>
    <action>/usr/sbin/cups_shell &</action>
   </button>
  </hbox>
  <hbox>
   <text>
    <label>Setup CD and DVD reader and burner drives...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-cd.xpm</input>
    <action>/usr/sbin/cdburner-wizard &</action>
   </button>
  </hbox>
  <hbox>
   <text>
    <label>Setup a firewall...</label>
   </text>
   <button>
    <input file>/usr/local/lib/X11/mini-icons/mini-firewall.xpm</input>
    <action>rxvt -e /usr/sbin/firewallinstallshell &</action>
   </button>
  </hbox>


  <hbox>
   <button><input file>/usr/local/lib/X11/mini-icons/mini.exit.xpm</input></button>
  </hbox>
 </vbox>
</window>
"

#echo "$WizardWizard" | gtkdialog --stdin
gtkdialog3 --program=WizardWizard

unset WizardWizard
